### ISSUE TITLE
Entrega Trabajo Práctico N°1

### ISSUE THREAD

**Issue by caroblanco** [caroblanco/2020_K2001_Grupo_2#1]
solicitamos la corrección del tp @santiagoferreiros

**Comment by santiagoferreiros** [comment]
@caroblanco @EstebanDer @camiguillan @Ezequiel-H 

Estimados,

Nota del trabajo: 6

Les comento porqué,

El trabajo cumple con la funcionalidad, pero no implementa el AFD que pide la consigna a través de su tabla de transición como matriz. La idea está muy bien, pero la mejor forma de organizar la información a es a través de una matriz que represente la tabla de transición TT
TT [Estado][Columna]
De esa forma, sabiendo en qué estado están, y la columna que le corresponde al caracter pueden conocer el estado siguiente.

El trabajo se los considero aprobado, pero si desean mejorar la nota deberían cambiar la lógica para implementar un AFD. Eso les sirve para los otros trabajos, además, en el caso de que tengan que implementar más LR deberían utilizar una tabla si o si, porque sino se les haría una locura de IF anidados por todos lados.

Saludos =)

**Comment by caroblanco** [comment]
Buenas tardes @santiagoferreiros ! En la carpeta del TP1 habia dos archivos, y en uno de ellos intentamos implementar la matriz y el otro habia sido nuestro primer intento sin ella. Puede ser que hayas visto el que no tenia la matriz? ahora borre el anterior y deje el que probamos con la matriz. En caso de que hayas visto el de la matriz, si esta mal implementada podrias darnos alguna pista de como hacerlo?
Desde ya, gracias
Carolina :)

**Comment by santiagoferreiros** [comment]
Carolina,
Ahí vi el otro trabajo, está muy bien la implementación. Es la forma en la que les comentaba. 
Excelente trabajo ! Cumple con todo ! FELICITACIONES =) Y a seguir trabajando así !
Nota: 10 !
@caroblanco @EstebanDer @camiguillan @Ezequiel-H
