### ISSUE TITLE
TP2

### ISSUE THREAD

**Issue by caroblanco** [caroblanco/2020_K2001_Grupo_2#2]
hola @santiagoferreiros ! Solicitamos la correcion del TP2. Dentro de la carpeta hay dos versiones diferentes, una muestra hasta donde esta el error, y lo indica,  y la otra dice si es valida o no. Sin embargo, ambas tienen estructuras diferentes y no sabemos cual seria la mas conveniente para el futuro.
desde ya, gracias

**Comment by santiagoferreiros** [comment]
Estimados

Es mejor la segunda implementación desde el punto de vista del AFP
Han hecho un gran trabajo. Felicitaciones !!!

Nota: 8

Vayan pensando para la próxima que según el estado donde finalice y que hay en la pila es el tipo de error. Ya lo iremos trabajando =)

Saludos

@caroblanco  @EstebanDer @camiguillan @Ezequiel-H

**Comment by caroblanco** [comment]
Hola @santiagoferreiros ! Queriamos consultarte cuales serian los errores en este TP, o lo que podriamos implementar para que sea mejor. 
Desde ya, gracias!
El grupo 2 del curso K2001

**Comment by santiagoferreiros** [comment]
Carolina,

Según el estado de error al cual llegó y lo que había en la cima de la pila podrían determinar que tipo de error sintáctico ocurrió.

Se espera OPERADOR y se recibió otro caracter
FALTA cierre de paréntesis
HAY un paréntesis de cierre demás que no corresponde a ninguno de apertura
Se espera NÚMERO y se recibió otro operador

Es decir, clasificar los errores.

Igual su trabajo está excelente ! =)
