### ISSUE TITLE
TP3

### ISSUE THREAD

**Issue by caroblanco** [caroblanco/2020_K2001_Grupo_2#3]
@santiagoferreiros hola profe!
Solicitamos la correccion del tp3. Creemos que no funciona bien por el insertar lista, y no sabemos como mejorarlo. Podria darnos una mano?
desde ya, gracias! :)

**Comment by santiagoferreiros** [comment]
Estimado grupo

Disculpen la demora.
Les parece bien reunirnos el próximo lunes luego de clase para ver que está pasando con el código?
Espero confirmación.
Saludos,

Santiago

**Comment by caroblanco** [comment]
@santiagoferreiros buenisimo profe! Hablamos el lunes. Muchas gracias

**Comment by caroblanco** [comment]
@santiagoferreiros hola profe! corregimos lo que pudimos del tp y sigue sin funcionar, de todas formas consideramos que la idea sobre la que realizamos el tp es acertada asi que solicitamos correccion. 
saludos, Carolina

**Comment by santiagoferreiros** [comment]
Estimado equipo !

La lógica del código es correcta y está bien organizado.
No puedo ver en detalle el error por una cuestión de tiempos.
Les sugiero que todas las ERX las tomen para empezar el TP 4 cuando lo comencemos la próxima clase.

Nota: 7

Buena predisposición y preocupación del equipo por avanzar a pesar de que la entrega sea opcional. Lamento no poder decir el tiempo a cada grupo. Sigamos con el TP 4.

Aconsejo que alguno siga trabajando con el TP 3 para resolver el tema de las listas.
Igual iremos viendo algunos ejemplos en clase

Saludos
