### ISSUE TITLE
correcion TP4

### ISSUE THREAD

**Issue by caroblanco** [caroblanco/2020_K2001_Grupo_2#4]
@santiagoferreiros  hola profe! Solicitamos la correccion del TP4. Saludos! :3

**Comment by santiagoferreiros** [comment]
Estimado grupo

Hay hecho un buen trabajo.
En el reporte les pido que agreguen el número de línea donde encuentra cada una de las cosas. 
Pueden utilizar una variable que cada vez que el analizador léxico encuentro en '\n' se pueda sumar en algún lado un contador en uno. De esa forma es más sencillo comprender el reporte. Sino quedan un poco perdidas las cosas.

El resto parece estar bien.
Vamos por más para el trabajo práctico integrador.

Nota: 9

Saludos,
Santiago
