### ISSUE TITLE
lista de parametros en una funcion

### ISSUE THREAD

**Issue by caroblanco** [caroblanco/2020_K2001_Grupo_2#5]
Hola @santiagoferreiros ! Tenemos un problema, no estamos logrando guardar solamente los parametros de una funcion. Podemos distinguir los tipos de variables pero no podemos distinguir cuales pertenecen a la funcion. Nos podrias ayudar?
Saludos, 
             el grupo 2 :D

**Comment by santiagoferreiros** [comment]
Hola grupo 2 

Primero que nada, les recomiendo separar en la gramática la declaración de variables respecto de la declaración de funciones.

La declaración de una función puede ser así

TIPO_DATO {almacenan el tipo} IDENTIFICADOR '(' lista_parametros ')' ';' {agregan la función a la TS con la lista de parámetros ya armada}

lista_parametros: TIPO_DATO IDENTIFICADOR {codigo C para agregarlo a la lista de parámetros}
                            | lista_parametros , TIPO_DATO IDENTIFICADOR {código C para agregarlo a la lista de parámetros}

La estructura de la TS puede ser la siguiente

![image](https://user-images.githubusercontent.com/46604718/99087040-1069c500-25a9-11eb-8aa7-9a6fb773c4c3.png)

Espero ayudarlos con esas guías,
Saludos,

Santiago

**Comment by caroblanco** [comment]
Hola @santiagoferreiros ! Hicimos lo que nos dijiste, y funciono, detectando bien los parametros y los tipos de las funciones, peeeeeeeeeeero ahora las declaraciones de variables se rompieron. Si comentamos la produccion de la declaracionFunciones al principio, lee las variables bien, pero sino, no entra a las reglas que le corresponden. 
Desde ya, gracias :3

**Comment by caroblanco** [comment]
Buen dia profe, ya pudimos solucionar el problema :)
Buen finde!

**Comment by santiagoferreiros** [comment]
Excelente que lo pudieron resolver :)
